### ISSUE TITLE
Linux: gcc build fails

### ISSUE THREAD

**Issue by nicholas-rh** [o3de/o3de#16153]
**Describe the bug**
The build fails using g++, gcc version 13.1.1 on Fedora 38. The first set of errors seem to be related to the different gcc builtins (__builtin_memcpy, __builtin_strlen, etc.) when called from a constexpr context. Since these functions aren't declared constexpr this results in a compile error:
```
/home/user1/o3de/Code/Framework/AzCore/./AzCore/std/string/string_view.h:531:29: error: ‘__builtin_memcpy(((void*)(&‘result_decl’ not supported by dump_expr<expression error>.AZStd::basic_fixed_string<char, 3, AZStd::char_traits<char> >::m_buffer)), ((const void*)(& numberString.AZStd::basic_fixed_string<char, 3, AZStd::char_traits<char> >::m_buffer)), 4)’ is not a constant expression
  531 |             __builtin_memcpy(dest, src, count * sizeof(char_type));
      |             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
These can be fixed by patching Code/Framework/AzCore/AzCore/PlatformDef.h to remove the check for gcc version identifier AZ_COMPILER_GCC >= 130000 for each of the __builtin functions. Here is a relevant gcc bug discussion: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94082

After patching those errors, the next error I get is:
```
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:138:26: error: explicit specialization in non-namespace scope ‘struct AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>’
  138 |                 template<>
      |                          ^
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:139:34: error: template-id ‘Create<VkRenderPassCreateInfo>’ in declaration of primary template
  139 |                 RenderPassResult Create<VkRenderPassCreateInfo>(VkRenderPassCreateInfoType& createInfo)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:148:26: error: explicit specialization in non-namespace scope ‘struct AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>’
  148 |                 template<>
      |                          ^
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:149:34: error: template-id ‘Create<VkRenderPassCreateInfo2>’ in declaration of primary template
  149 |                 RenderPassResult Create<VkRenderPassCreateInfo2>(VkRenderPassCreateInfoType& createInfo)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:149:34: error: ‘AZ::Vulkan::Internal::RenderPassResult AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>::Create(VkRenderPassCreateInfoType&)’ cannot be overloaded with ‘AZ::Vulkan::Internal::RenderPassResult AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>::Create(VkRenderPassCreateInfoType&)’
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:139:34: note: previous declaration ‘AZ::Vulkan::Internal::RenderPassResult AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>::Create(VkRenderPassCreateInfoType&)’
  139 |                 RenderPassResult Create<VkRenderPassCreateInfo>(VkRenderPassCreateInfoType& createInfo)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:219:26: error: explicit specialization in non-namespace scope ‘struct AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>’
  219 |                 template<>
      |                          ^
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:220:22: error: template-id ‘BuildAttachmentReferences<AZ::Vulkan::Internal::AttachmentType::Preserve>’ in declaration of primary template
  220 |                 void BuildAttachmentReferences<AttachmentType::Preserve>(uint32_t subpassIndex, SubpassInfo& subpassInfo) const
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:304:26: error: explicit specialization in non-namespace scope ‘struct AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>’
  304 |                 template<>
      |                          ^
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:305:22: error: template-id ‘SetFragmentShadingRateAttachmentInfo<VkAttachmentReference2>’ in declaration of primary template
  305 |                 void SetFragmentShadingRateAttachmentInfo<VkAttachmentReference2>(
      |                      ^~~~~~~~~~~~

```
I'll update with a comment once I look more into this error and see if any others pop up.

**Steps to reproduce**
1. Attempt to build using gcc version 13.1.1 (or potentially any recent version of gcc)
2. The build will fail at compile time

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
7c3c66db9c01a162c3847e828d301f63360d7a96

**Desktop/Device (please complete the following information):**
- OS: Fedora 38
- gcc (dnf info):
```
Installed Packages
Name         : gcc
Version      : 13.1.1
Release      : 2.fc38
Architecture : x86_64
Size         : 92 M
Source       : gcc-13.1.1-2.fc38.src.rpm
Repository   : @System
From repo    : updates
Summary      : Various compilers (C, C++, Objective-C, ...)
URL          : http://gcc.gnu.org
License      : GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
Description  : The gcc package contains the GNU Compiler Collection version 13.
             : You'll need this package in order to compile C code.
```

**Comment by lumberyard-employee-dm** [comment]
I just fixed this the __builtin_memcpy in this commit that went in yesterday https://github.com/o3de/o3de/commit/e3ba1e1e61156b5e215bcab2bb27d97b1bbced5b#diff-d270ee4ecc461abf340b628cc3a58c0581dbd3aacab47cb8266f84b1d0f1cbe3

I have local changes to fix the Atom_RHI.Vulkan compilation for the explicit template specialization inside class issue
