### PR TITLE
Update engine code to C++20

### PR DESCRIPTION
**Pull request by mprettner-huawei**
## What does this PR do?

This PR updates the codebase to use c++20 and fixes all remaining compile errors.

There were already many c++20 compile errors fixed in [PR18994](https://github.com/o3de/o3de/pull/18994), but it appears that not all errors were fixed (at least for the configurations which I tested).
If the actual change to c++20 for O3DE is not desirable at this time, the last commit could be omitted.

Detailed changes (One bullet point per commit):
* Make Crc32 single parameter constructors explicit: There were many instances of ambiguous comparison operations between `AZ::Crc32`, ingegral types, and classes which could implicitly be created from `AZ::Crc32`; because Crc32 had both an implicit constructor with a single `uint32_t` parameter and an implicit `operator uint32_t()` conversion operator
* Explicitly convert utf8-encoded string literals to const char*: utf8 string literals need to use the `u8` prefix, but they are no longer implicitly converted to `const char*, hence the additional `reinterpret_cast` operators
* Change deprecated atomic_init to atomic_store
* Fix failing implicit conversion operations: Miscellaneous fixes from less aggressive implicit conversion operator usage
* Fix pair constructor errors: `is_convertible_v` does not seem to work with values, only types
* Change variant implementation to std::variant: There were some really strange compile errors in the O3DE variant implementation when using variants in a constexpr context, which I was not able to solve by modifying existing code. Using the standard-library variant seemed to be a reasonable alternative.
* Add constructors to structs which can no longer be aggregate-initialized: This only affected a single test file
* Remove spaces from user-defined string literals operators: This is currently only necessary for Clang20 , (https://godbolt.org/z/84P9vPW86), which is not the main goal of this PR but will be necessary later
* Add option to disable deprecated enum-enum-conversion warnings for 3rd-party dependencies: The Whitebox gem includes some OpenMesh headers, which use these deprecated enum conversions
* Fix fixed_vector insertion with ranges::view: Use the same implementation as in `AZStd::vector` for inserting a range to the fixed_vector
* Fix usages of deprecated increment/decrement operators for volatile types: Not sure what the purpose of these volatile values actually is, or if they should rather be atomic values
* Temporarily disable warning for deprecated this-capture: There are currently >100 instances of the `[=]` and `[&]` lambda captures, many of which would need to be updated to fix this warning. To keep this PR as small as possible, this work has been deferred and the warning temporary disabled
* Fix remaining compile errors: Random assortment of the remaining compile errors, most notable `Atom/RHI/DX12/.../CommandList.h/.cpp, which did not compile due to an indirect circular depencency between DX12::CommandList and DX12::Device
* Change C++ standard to C++20: This commit actually changes the c++ version in CMake

## How was this PR tested?

Compile with MSVC (19.36.32548.0, 19.44.35211.0) and Clang 19 on Windows, compile with Clang19 on Linux.

### CODE REVIEW

**Comment by nick-l-o3de** [comment]
Are there any supported platforms that do not yet support c++20? 

I looked at MSVC2019 which is listed under supported, and the latest MSVC2019 appears to support c++20.
I looked at MSVC2022 and yeah, that looks like it supports c++20

Clang 18 (minimum supported version under ubuntu 22.04 I believe) has 'partial support' for C++20 but I'm not sure what that even means.

Basically, do these changes mandate C++20 is required now, or do they simply make it c++20 compatible and can still compile under c++17?

**Comment by msat-huawei** [comment]
> I looked at MSVC2019 which is listed under supported, and the latest MSVC2019 appears to support c++20. I looked at MSVC2022 and yeah, that looks like it supports c++20
> 
> Clang 18 (minimum supported version under ubuntu 22.04 I believe) has 'partial support' for C++20 but I'm not sure what that even means.

Partial means that not all features of C++20 are supported, but some. Cppreference has a nice table about which compilers support which C++20 features: https://en.cppreference.com/w/cpp/compiler_support/20
According to this Clang 18 supports almost all C++20 features.
The same is true vor MSVC2019.

**Comment by mprettner-huawei** [comment]
I managed to fix all CI compilation errors, now there are only two tests failing on Windows. I will wait for [PR19111](https://github.com/o3de/o3de/pull/19111) to be merged, and then rebase on development.

File: cmake/Configurations.cmake [hunk 1]
```diff
@@ -170,7 +170,7 @@ function(ly_append_configurations_options)
 endfunction()
 
 # Set the C++ standard that is being targeted to C++17
-set(CMAKE_CXX_STANDARD 17 CACHE STRING "C++ Standard to target")
+set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ Standard to target")
```
Comment (jhanca-robotecai) [inline cmake/Configurations.cmake:173]: Please update the comment above to ensure there is no confusion.

File: cmake/Platform/Common/Clang/Configurations_clang.cmake [hunk 2]
```diff
@@ -50,6 +54,7 @@ ly_append_configurations_options(
         -Wno-undefined-var-template
         -fno-relaxed-template-template-args
         -Wno-deprecated-no-relaxed-template-template-args
+        -Wno-deprecated-this-capture # TODO(c++20): Remove this
```
Comment (jhmueller-huawei) [inline cmake/Platform/Common/Clang/Configurations_clang.cmake:57]: For when is this TODO?

File: cmake/Platform/Common/MSVC/Configurations_msvc.cmake [hunk 3]
```diff
@@ -81,6 +85,7 @@ ly_append_configurations_options(
         #/we4619 # #pragma warning: there is no warning number 'number'. Unfortunately some versions of MSVC 16.X dont filter this warning coming from external headers and Qt has a bad warning in QtCore/qvector.h(340,12)
         /we4774 # 'string' : format string expected in argument number is not a string literal
         /we4777 # 'function' : format string 'string' requires an argument of type 'type1', but variadic argument number has type 'type2
+        #/we4855 # implicit capture of 'this' via '[=]' is deprecated in 'version' TODO(c++20): Enable this
```
Comment (jhmueller-huawei) [inline cmake/Platform/Common/MSVC/Configurations_msvc.cmake:88]: For when is this TODO?

File: cmake/Platform/Common/Clang/Configurations_clang.cmake (hunk 2 above)
Comment (mprettner-huawei) [reply cmake/Platform/Common/Clang/Configurations_clang.cmake:57]: I will fix it after this PR, the Clang19 compile error fix [PR19150](https://github.com/o3de/o3de/pull/19150) and the upcoming Clang20 compile error PR are merged. I did not want to include it in this PR since it already changes more than 100 files.

File: cmake/Platform/Common/MSVC/Configurations_msvc.cmake (hunk 3 above)
Comment (mprettner-huawei) [reply cmake/Platform/Common/MSVC/Configurations_msvc.cmake:88]: Same as https://github.com/o3de/o3de/pull/19125#discussion_r2231094047

**Comment by mprettner-huawei** [comment]
All CI errors have been fixed, the PR is now ready for review.

File: Code/Framework/AzCore/AzCore/Serialization/DataPatch.h [hunk 4]
```diff
@@ -22,8 +22,8 @@ namespace AZ
         class AddressTypeSerializer;
 
         static constexpr const char PathDelimiter[] = "/";
-        static constexpr const char VersionDelimiter[] = u8"\u00B7"; // utf-8 for <middledot>
-        
+        static inline const char* VersionDelimiter = reinterpret_cast<const char*>(u8"\u00B7"); // utf-8 for <middledot>
```
Comment (spham-amzn) [inline Code/Framework/AzCore/AzCore/Serialization/DataPatch.h:25]: If this worked, we should consider changing the `PathDelimiter[]` line above to a `static inline const char*` as well

File: Code/Framework/AzCore/AzCore/std/ranges/iota_view.h [hunk 5]
```diff
@@ -272,21 +272,70 @@ namespace AZStd::ranges
...
+                }
+                else
+                {
+                    if (n >= difference_type(0))
+                    {
+                        m_value += static_cast<W>(n);
+                    }
+                    else
+                    {
+                        m_value -= static_cast<W>(-n);
```
Comment (spham-amzn) [inline Code/Framework/AzCore/AzCore/std/ranges/iota_view.h:292]: Isn't `x += y` the same thing as ` x -= -y` ? Maybe explain in a comment what is going on here.

**Review by lsemp3d — APPROVED** [review]

File: Code/Framework/AzCore/AzCore/std/ranges/iota_view.h (hunk 5 above)
Comment (jhmueller-huawei) [reply Code/Framework/AzCore/AzCore/std/ranges/iota_view.h:292]: `W` is an unsigned type and since `n` is negative, we need to make sure it's positive before subtracting it from `m_value`.

Comment (mprettner-huawei) [reply Code/Framework/AzCore/AzCore/std/ranges/iota_view.h:292]: This is basically the same set of steps that LLVM does ([source](https://github.com/llvm/llvm-project/blob/main/libcxx/include/__ranges/iota_view.h#L162)) to ensure all combinations of signed/unsigned work properly.

File: Code/Framework/AzCore/AzCore/Serialization/DataPatch.h (hunk 4 above)
Comment (mprettner-huawei) [reply Code/Framework/AzCore/AzCore/Serialization/DataPatch.h:25]: Changed `VersionDelimiter` to `static inline const char*`

File: Code/Framework/AzCore/AzCore/std/ranges/iota_view.h (hunk 5 above)
Comment (mprettner-huawei) [reply Code/Framework/AzCore/AzCore/std/ranges/iota_view.h:292]: I added a comment explaining these two branches in `operator+=` and `operator-=` of ranges::iota_view.
