### PR TITLE
GCC 13/Clang 14 build fixes

### LINKED ISSUE #16153: Linux: gcc build fails
**Describe the bug**
The build fails using g++, gcc version 13.1.1 on Fedora 38. The first set of errors seem to be related to the different gcc builtins (__builtin_memcpy, __builtin_strlen, etc.) when called from a constexpr context. Since these functions aren't declared constexpr this results in a compile error:
```
/home/user1/o3de/Code/Framework/AzCore/./AzCore/std/string/string_view.h:531:29: error: ‘__builtin_memcpy(((void*)(&‘result_decl’ not supported by dump_expr<expression error>.AZStd::basic_fixed_string<char, 3, AZStd::char_traits<char> >::m_buffer)), ((const void*)(& numberString.AZStd::basic_fixed_string<char, 3, AZStd::char_traits<char> >::m_buffer)), 4)’ is not a constant expression
  531 |             __builtin_memcpy(dest, src, count * sizeof(char_type));
      |             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
These can be fixed by patching Code/Framework/AzCore/AzCore/PlatformDef.h to remove the check for gcc version identifier AZ_COMPILER_GCC >= 130000 for each of the __builtin functions. Here is a relevant gcc bug discussion: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94082

After patching those errors, the next error I get is:
```
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:138:26: error: explicit specialization in non-namespace scope ‘struct AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>’
  138 |                 template<>
      |                          ^
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:139:34: error: template-id ‘Create<VkRenderPassCreateInfo>’ in declaration of primary template
  139 |                 RenderPassResult Create<VkRenderPassCreateInfo>(VkRenderPassCreateInfoType& createInfo)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:148:26: error: explicit specialization in non-namespace scope ‘struct AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>’
  148 |                 template<>
      |                          ^
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:149:34: error: template-id ‘Create<VkRenderPassCreateInfo2>’ in declaration of primary template
  149 |                 RenderPassResult Create<VkRenderPassCreateInfo2>(VkRenderPassCreateInfoType& createInfo)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:149:34: error: ‘AZ::Vulkan::Internal::RenderPassResult AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>::Create(VkRenderPassCreateInfoType&)’ cannot be overloaded with ‘AZ::Vulkan::Internal::RenderPassResult AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>::Create(VkRenderPassCreateInfoType&)’
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:139:34: note: previous declaration ‘AZ::Vulkan::Internal::RenderPassResult AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>::Create(VkRenderPassCreateInfoType&)’
  139 |                 RenderPassResult Create<VkRenderPassCreateInfo>(VkRenderPassCreateInfoType& createInfo)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:219:26: error: explicit specialization in non-namespace scope ‘struct AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>’
  219 |                 template<>
      |                          ^
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:220:22: error: template-id ‘BuildAttachmentReferences<AZ::Vulkan::Internal::AttachmentType::Preserve>’ in declaration of primary template
  220 |                 void BuildAttachmentReferences<AttachmentType::Preserve>(uint32_t subpassIndex, SubpassInfo& subpassInfo) const
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:304:26: error: explicit specialization in non-namespace scope ‘struct AZ::Vulkan::Internal::VkRenderpassBuilder<VkRenderPassCreateInfoTraits, VkAttachmentDescriptionTraits, VkAttachmentReferenceTraits, VkSubpassDescriptionTraits, VkSubpassDependencyTraits>’
  304 |                 template<>
      |                          ^
/home/user1/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:305:22: error: template-id ‘SetFragmentShadingRateAttachmentInfo<VkAttachmentReference2>’ in declaration of primary template
  305 |                 void SetFragmentShadingRateAttachmentInfo<VkAttachmentReference2>(
      |                      ^~~~~~~~~~~~

```
I'll update with a comment once I look more into this error and see if any others pop up.

**Steps to reproduce**
1. Attempt to build using gcc version 13.1.1 (or potentially any recent version of gcc)
2. The build will fail at compile time

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
7c3c66db9c01a162c3847e828d301f63360d7a96

**Desktop/Device (please complete the following information):**
- OS: Fedora 38
- gcc (dnf info):
```
Installed Packages
Name         : gcc
Version      : 13.1.1
Release      : 2.fc38
Architecture : x86_64
Size         : 92 M
Source       : gcc-13.1.1-2.fc38.src.rpm
Repository   : @System
From repo    : updates
Summary      : Various compilers (C, C++, Objective-C, ...)
URL          : http://gcc.gnu.org
License      : GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
Description  : The gcc package contains the GNU Compiler Collection version 13.
             : You'll need this package in order to compile C code.
```

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
GCC 13 Build Fixes

Most of the changes are around unused variables or potential dangling references.

The dangling references case occurs when a function that return a value, then invokes a function that returns a reference.

fixes #16153

Clang 14+ build fixes in relation to variables that are only set, but never read.

## How was this PR tested?

Built O3DE using GCC13 on ArchLinux

### CODE REVIEW

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp [hunk 1]
```diff
@@ -113,7 +111,6 @@ namespace AzToolsFramework
                         // sources with no children should be greyed out.
                         if (sourceEntry->GetChildCount() == 0)
                         {
-                            isEnabled = false; // draw in disabled style.
                             actualPalette.setCurrentColorGroup(QPalette::Disabled);
```
Comment (AMZN-alexpete) [inline Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp:114]: I think `actualPallete` is no longer used now either and I'm surprised it isn't causing an unused var error

File: Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshInputBuffers.cpp [hunk 2]
```diff
@@ -180,7 +182,8 @@ namespace AZ
         void SkinnedMeshInputLod::TrackStaticBufferViews(uint32_t meshIndex)
         {
             SkinnedSubMeshProperties& skinnedSubMesh = m_meshes[meshIndex];
-            const RPI::ModelLodAsset::Mesh& modelLodAssetMesh = m_modelLodAsset->GetMeshes()[meshIndex];
+            const auto modelLodAssetMeshes = m_modelLodAsset->GetMeshes();
+            const RPI::ModelLodAsset::Mesh& modelLodAssetMesh = modelLodAssetMeshes[meshIndex];
```
Comment (lumberyard-employee-dm) [inline Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshInputBuffers.cpp:186]: The reason GCC sees this code as a potential dangling reference is because the [GetMeshes](https://github.com/o3de/o3de/blob/9730572ef3909d48e8c945fbdd29c0e6b7e5ed6f/Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Model/ModelLod.h#L96) function returns an `AZStd::span<const Mesh>`.

Now the compiler doesn't know the semantics of the `AZStd::span` span type, so it can't know that invoking the [T& operator[]](https://github.com/o3de/o3de/blob/9730572ef3909d48e8c945fbdd29c0e6b7e5ed6f/Code/Framework/AzCore/AzCore/std/containers/span.h#L156-L157) function is returning a reference to a view-like type which is safe.

It only knows that the type being returned is a value type and then a function being invoked on it is then returning a reference to that value.

File: Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp [hunk 3]
```diff
@@ -194,40 +196,42 @@ namespace AZ
                 template<AttachmentType type>
                 void BuildAttachmentReferences(uint32_t subpassIndex, SubpassInfo& subpassInfo) const
                 {
-                    AZStd::span<const RenderPass::SubpassAttachment> subpassAttachmentList = GetSubpassAttachments(subpassIndex, type);
-                    AZStd::vector<VkAttachmentReferenceType>& attachmentReferenceList =
-                        subpassInfo.m_attachmentReferences[static_cast<uint32_t>(type)];
-                    attachmentReferenceList.resize(subpassAttachmentList.size());
-                    for (uint32_t index = 0; index < subpassAttachmentList.size(); ++index)
+                    // A template cannot be specialized inside of another template
+                    // therefore if constexpr is used to filter the Preserve AttachmentType functionality
```
Comment (AMZN-alexpete) [inline Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:200]:
```suggestion
                    // therefore constexpr is used to filter the Preserve AttachmentType functionality
```

File: Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp (hunk 1 above)
Comment (lumberyard-employee-dm) [reply Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp:114]: The reason that `actualPalette` variable doesn't cause an unused variable warning is that the compiler can only determine variable usage for the function it is compiling.
Since a member function is called using `actualPalette` variable, the compiler has to assume that there are side effects to calling other functions that might affect global state(such as accessing as the function calling `QCoreApplication::instance()` and changing the QT state)`

File: Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp (hunk 3 above)
Comment (lumberyard-employee-dm) [reply Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:200]: The "if" was not a typo.
The comment is meant to say "if constexpr" as in the `if constexpr` block in the code.

File: Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialAssignment.cpp [hunk 4]
```diff
@@ -214,8 +214,12 @@ namespace AZ
                 return lodAssignment;
             }
 
+            // GCC is incorrectly flaging the const reference returned from GetMaterialAssignmentFromMap
```
Comment (AMZN-alexpete) [inline Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialAssignment.cpp:217]:
```suggestion
            // GCC is incorrectly flagging the const reference returned from GetMaterialAssignmentFromMap
```

**Review by AMZN-alexpete — APPROVED** [review]
Just some minor things

File: Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp (hunk 3 above)
Comment (mbalfour-amzn) [inline Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:200]: I tripped up while reading this too, maybe just add quotes around it?

```suggestion
                    // therefore 'if constexpr' is used to filter the Preserve AttachmentType functionality
```

File: Gems/PhysX/Code/Include/PhysX/EditorColliderComponentRequestBus.h [hunk 5]
```diff
@@ -217,9 +217,9 @@ namespace PhysX
         virtual void ValidateRigidBodyMeshGeometryType() = 0;
     };
 
-    AZ_PUSH_DISABLE_WARNING(4996, "-Wdeprecated-declarations")
+    AZ_PUSH_DISABLE_WARNING(4996, "-Wdeprecated-declarations", "-Wdeprecated-declarations");
```
Comment (mbalfour-amzn) [inline Gems/PhysX/Code/Include/PhysX/EditorColliderComponentRequestBus.h:220]: This is a weird change but I assume correct?

**Review by mbalfour-amzn — APPROVED** [review]
Approved with the assumption that the one shadowed variable called out by someone else gets fixed.

File: Gems/PhysX/Code/Include/PhysX/EditorColliderComponentRequestBus.h (hunk 5 above)
Comment (spham-amzn) [reply Gems/PhysX/Code/Include/PhysX/EditorColliderComponentRequestBus.h:220]: The second argument i think is for gcc compilation

File: Code/Legacy/CryCommon/IMovieSystem.h [hunk 6]
```diff
@@ -120,18 +120,18 @@ class CAnimParamType
```
Comment (spham-amzn) [inline Code/Legacy/CryCommon/IMovieSystem.h:120]: I thought IMovieSystem wouldve been red-coded by now

**Review by spham-amzn — APPROVED** [review]

File: Gems/Atom/RHI/Vulkan/Code/Source/RHI/GraphicsPipeline.cpp [hunk 7]
```diff
@@ -200,16 +202,17 @@ namespace AZ
...
-                     if (chanDesc.m_bufferIndex == index)
-                     {
-                         desc.stride += GetFormatSize(chanDesc.m_format);
-                     }
-                 }
+                const auto& streamChannels = inputStreamLayout.GetStreamChannels();
+
+                for (uint32_t channelIndex = 0; channelIndex < streamChannels.size(); ++channelIndex)
+                {
+                    const auto streamChannels = inputStreamLayout.GetStreamChannels();
```
[the remark this answers is not in the document]
Comment (lumberyard-employee-dm) [reply Gems/Atom/RHI/Vulkan/Code/Source/RHI/GraphicsPipeline.cpp:209]: I missed that.
Will fix.

File: Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp (hunk 3 above)
Comment (lumberyard-employee-dm) [reply Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp:200]: I'll add backticks around it, so that if comment is ever extracted to doxygen it would show up as a code snippet.

File: Gems/PhysX/Code/Include/PhysX/EditorColliderComponentRequestBus.h (hunk 5 above)
Comment (lumberyard-employee-dm) [reply Gems/PhysX/Code/Include/PhysX/EditorColliderComponentRequestBus.h:220]: Yes, the second argument only applies to Clang.
The third argument is needed to apply the warning suppression to GCC.

Also the clang warning suppression arguments do **NOT** always map to GCC warning suppression arguments.

While mapping `-Wdeprecated-declarations` to both Clang and GCC works, it doesn't work for other arguments such as `-Wunknown-warning-option`.

So the 2 argument `AZ_PUSH_DISABLE_WARNING` macro cannot be extended to work for both Clang and GCC transparently.

File: Code/Legacy/CryCommon/IMovieSystem.h (hunk 6 above)
Comment (lumberyard-employee-dm) [reply Code/Legacy/CryCommon/IMovieSystem.h:120]: I thought Maestro would have been recorded for now, but it still has it's tentacles in the Editor code.

**Review by moudgils — APPROVED** [review]

**Review by Jackie9527 — APPROVED** [review]
LGTM
