### ISSUE TITLE
AssetProcessorMessagesTests are failing to compile on MSVC 14.44.35207 with a warning treated as error (C2220)

### ISSUE THREAD

**Issue by amzn-changml** [o3de/o3de#19096]
**Describe the bug**
AssetProcessorMessagesTests are failing to compile on MSVC 14.44.35207 with a warning treated as error (C2220)

**Assets required**
- GHA AR runner using runner image: `20250620.352`
- UCRTVersion: `10.0.26100.0`
- VCToolsVersion: `14.44.35207`
- VisualStudioVersion: `17.0`

**Steps to reproduce**
1. Run GHA AR on merged build or PR
2. Let run complete for Windows release
3. See error

**Expected behavior**
No failures in compilation

**Actual behavior**
Error messages below:
```
E:\o3de\Code\Tools\AssetProcessor\native\tests\AssetProcessorMessagesTests.cpp(167,147): error C2220: the following warning is treated as an error [E:\o3de\build\windows\Code\Tools\AssetProcessor\AssetProcessor.Tests.vcxproj]
              QObject::connect(m_batchApplicationManager->m_connectionManager, &ConnectionManager::ConnectionError, [](unsigned /*connId*/, QString error)
                                                                                                                                                    ^ (compiling source file '../../../Code/Tools/AssetProcessor/CMakeFiles/AssetProcessor.Tests.dir/Unity/unity_3_cxx.cxx')
  
E:\o3de\Code\Tools\AssetProcessor\native\tests\AssetProcessorMessagesTests.cpp(167,147): warning C4100: 'error': unreferenced parameter [E:\o3de\build\windows\Code\Tools\AssetProcessor\AssetProcessor.Tests.vcxproj]
              QObject::connect(m_batchApplicationManager->m_connectionManager, &ConnectionManager::ConnectionError, [](unsigned /*connId*/, QString error)
                                                                                                                                                    ^ (compiling source file '../../../Code/Tools/AssetProcessor/CMakeFiles/AssetProcessor.Tests.dir/Unity/unity_3_cxx.cxx')

E:/o3de/Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp(167,147): error C2220: the following warning is treated as an error [E:\o3de\build\windows\Code\Tools\AssetProcessor\AssetProcessor.Tests.vcxproj]
              QObject::connect(m_batchApplicationManager->m_connectionManager, &ConnectionManager::ConnectionError, [](unsigned /*connId*/, QString error)
                                                                                                                                                    ^
E:/o3de/Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp(167,147): warning C4100: 'error': unreferenced parameter [E:\o3de\build\windows\Code\Tools\AssetProcessor\AssetProcessor.Tests.vcxproj]
```

**Screenshots/Video**
Link to AR run: 
- https://github.com/o3de/o3de/actions/runs/15986060976/job/45138193759#step:16:2375
- https://github.com/o3de/o3de/actions/runs/15986060976/job/45138193759#step:16:2563

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Not directly caused, but started to appear in https://github.com/o3de/o3de/commit/747a6c56ccb233653859cabdd7643c65ceb23b86

**Desktop/Device (please complete the following information):**
 - Device: Github Action Runner
 - OS: Windows Server 2019
 - Version `20250620.352`
 - CPU: Intel 4-core
 - GPU: N/A
 - Memory: 16GB

**Additional context**
