### PR TITLE
Fix vulkan fence synchronization

### PR DESCRIPTION
**Pull request by msat-huawei**
## What does this PR do?

This fixes issues related to synchronization of VkFence and binary semaphores introduced by https://github.com/o3de/o3de/pull/17761 , when a device without timeline semaphore support is used:
1. Re-added synchronization to fences used in the Vulkan async upload queue. The SignalEvent class of the Fence was formerly owned by the Fence itself. Now it must be supplied from outside the class.
2. In the case of waiting for a fence that is signaled from the framegraph, we did not wait for the fence itself to be signaled. Only the fences/semaphores it dependent upon. We now also wait for the fence itself to be signaled.

This PR should fix https://github.com/o3de/o3de/issues/17890. I cannot test this directly as I don't have access to a Quest. We however managed to fix multiple Vulkan validation warnings related to VkFence and multi threading.

## How was this PR tested?

Tested with various atom sample viewer samples, and some custom levels.
I couldn't get the OpenXRTest project to run, as mentioned in https://github.com/o3de/o3de/issues/17890. There are many passes/shaders that won't compile in the AssetProcessor. We managed to create Vulkan validation errors in some of the atom sample viewer samples however.

### CODE REVIEW

**Comment by galibzon** [comment]
I'm testing this PR now on a Quest Pro.

**Comment by galibzon** [comment]
I got this compilation error:
```
C:\GIT\o3de\Gems\Atom\RHI\Vulkan\Code\Source\RHI\AsyncUploadQueue.cpp(107,22): error C2220: the following warning is treated as an error [C:\GIT\o3de-extras\Projects\Op
enXRTest\build\External\Vulkan-4a6b04ec\Code\Atom_RHI_Vulkan.Private.Static.vcxproj]
                  auto signalEvent = AZStd::make_shared<SignalEvent>();
                       ^ (compiling source file '../Vulkan-4a6b04ec/Code/CMakeFiles/Atom_RHI_Vulkan.Private.Static.dir/Unity/unity_1_cxx.cxx')

C:\GIT\o3de\Gems\Atom\RHI\Vulkan\Code\Source\RHI\AsyncUploadQueue.cpp(107,22): warning C4456: declaration of 'signalEvent' hides previous local declaration [C:\GIT\o3de
-extras\Projects\OpenXRTest\build\External\Vulkan-4a6b04ec\Code\Atom_RHI_Vulkan.Private.Static.vcxproj]
                  auto signalEvent = AZStd::make_shared<SignalEvent>();
                       ^ (compiling source file '../Vulkan-4a6b04ec/Code/CMakeFiles/Atom_RHI_Vulkan.Private.Static.dir/Unity/unity_1_cxx.cxx')
  C:\GIT\o3de\Gems\Atom\RHI\Vulkan\Code\Source\RHI\AsyncUploadQueue.cpp(99,18):
  see declaration of 'signalEvent'
              auto signalEvent = AZStd::make_shared<SignalEvent>();
```

**Comment by galibzon** [comment]
Tested with OpenXRTest and it's working. Thanks a lot for taking care of this issue.

**Review by galibzon — APPROVED** [review]

**Comment by moudgils** [comment]
@msat-huawei Can we cherry pick this PR into stabilization branch. Thanks.
